### ISSUE TITLE
Bug: Odd error message on kustomization

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#1593] opened 2022-03-03 12:27 UTC
<img width="724" alt="Screenshot 2022-03-03 at 12 26 42" src="https://user-images.githubusercontent.com/19860021/156564520-b37b034f-0829-46e7-a684-f6bf2fb4493c.png">

Where are we getting this from?

Output from flux/message on the object is `Health check failed after 30.01174149s, timeout waiting for: [Deployment/test/backend status: 'Failed']`

**Comment by jpellizzari** [comment] 2022-03-03 16:56
@sympatheticmoose Can you look at your browser console and let me know what the /kustomization endpoint is returning?

**Comment by jpellizzari** [comment] 2022-03-03 17:19
This might actually be a CSS issue where the beginning of the message is getting truncated. Here is what I get:
![Screenshot from 2022-03-03 09-17-55](https://user-images.githubusercontent.com/2802257/156617005-034a4f64-3676-4459-9892-977abcc6c89f.png)

**Comment by jpellizzari** [comment] 2022-03-03 18:15
Nope, this is a valid message from the kustomize controller:

https://github.com/fluxcd/kustomize-controller/blob/f2f9395c4d7754144f48ac80a03bbba228a1dc32/controllers/kustomization_controller.go#L861

**Comment by sympatheticmoose** [comment] 2022-03-03 18:23
I'm not yet convinced. How frequent is our polling? The bug is that there is a different error message displayed here than is displayed through inspection of the object through kubectl/flux

**Comment by jpellizzari** [comment] 2022-03-03 19:57
A refresh of the page will demonstrate the behavior. I would bet that it will be in this state for 30s after the object is created or while it is running its timeout.

**Comment by jpellizzari** [comment] 2022-03-03 19:57
Re-opening until we are both convinced its working @sympatheticmoose

**Comment by rokshana-b** [comment] 2022-04-21 02:38
@sympatheticmoose How do we reproduce the steps to investigate this issue? It looks like the most recent changes on main does not even have a `status`:

![image.png](https://images.zenhubusercontent.com/606389351ead0c83798a9a73/20fc2249-37be-4a98-987d-204499599ef2)

**Comment by sympatheticmoose** [comment] 2022-04-21 08:59
@rokshana-b the status is shown in the top right of your screenshot. It was moved to allow for a larger error message.

In terms of recreating, all objects including this specific kustomization are in https://github.com/sympatheticmoose/gitops-error-scenarios/, kustomization: https://github.com/sympatheticmoose/gitops-error-scenarios/blob/main/clusters/my-cluster/kc-health-check/podinfo-deploy-2-bad-kustomization.yaml

My concern is that there seemed to be inconsistency/potentially timing related, in the error message depending on whether you queried using the Flux CLI or viewing in the UI.

**Comment by jpellizzari** [comment] 2022-04-22 14:46
Accidentally closed this

**Comment by rokshana-b** [comment] 2022-04-22 15:46
@sympatheticmoose I cloned your error-scenario repo and bootstrapped flux using that repo. This is what I got:

<img width="1695" alt="Screen Shot 2022-04-22 at 02 45 30" src="https://user-images.githubusercontent.com/76788247/164749080-3f4edec2-21e1-4195-8fe2-c4c13939dfb2.png">

<img width="739" alt="image" src="https://user-images.githubusercontent.com/76788247/164749187-1e46ebff-fe1b-49fb-bd27-9ff65bf8a191.png">

**Closed** 2022-09-15 13:10 UTC
Labels: ui
