### ISSUE TITLE
Exiting "gitops run" leaves terminal in indeterminate state

### ISSUE THREAD

**Issue by pfcurtis** [weaveworks/weave-gitops#3203] opened 2022-12-27 19:22 UTC
**Describe the bug**

Once "gitops run" has exited, the terminal (curses) state is not returned to the default.

**Environment**

- OS: macOS X
- Weave-Gitops Version 0.13
- Flux Version 0.37
- Kubernetes version 1.25

**To Reproduce**

1. Open a terminal window
2. Execute "gitops run"
3. Exit that using `<Ctrl-C>`

**Expected behavior**

Terminal curses state returned to default state.

**Actual Behavior**

Terminal requires a "tset" in order to have the terminal work properly. The common example is newlines are not returned to the terminal when the <Enter> (return) key is pressed. This normally due to the libcurses state not being reset prior to exiting the application.

**Additional Context (screenshots, logs, etc)**

**Comment by makkes** [comment] 2022-12-30 09:52
Thanks for filing this bug @pfcurtis. I have two requests:

1. Would you mind expaning on step three of the "To Reproduce" section, please? It currrently says "Exit that using".
2. At which point do you exit the `gitops` program? Would you mind pasting the terminal output from around that phase, please?

**Comment by pfcurtis** [comment] 2022-12-30 14:33
There was a "Ctrl-C" at the end of step 3.

I exit "gitops run" when I'm done with the session. Typically after I've committed and pushed the code.

**Comment by makkes** [comment] 2022-12-30 19:28
@pfcurtis Would you mind pasting the terminal output from around that phase, please?

**Comment by makkes** [comment] 2023-02-15 14:24
First thing to do here would be to try to reproduce it and gather some more information on the exact point in time where this happens.

**Comment by makkes** [comment] 2023-02-15 15:24
I'm  not able to reproduce this one. @chanwit is there a chance you can give it a try as you said you run into it from time to time?

**Comment by makkes** [comment] 2023-02-21 17:26
I tried all different ways to reproduce it but to not avail. Closing.

**Closed by makkes** 2023-02-21 17:26 UTC
Labels: bug, severity/high, ux, team/denim, gitops-run, mvp
