### ISSUE TITLE
`gitops beta run`: Errors when trying to run it again

### ISSUE THREAD

**Issue by pjbgf** [weaveworks/weave-gitops#3077] opened 2022-11-29 08:48 UTC
**Describe the bug**

`gitops beta run` fails with `dial tcp 127.0.0.1:37799: connect: connection refused` when executed again after a successful execution. 

**Environment**

- Weave-Gitops Version: `v0.11.0`
- Flux Version: `v0.36.0` (installed by gitops)
- Kubernetes version: `kindest/node:v1.25.3`

**To Reproduce**

```sh
$ kind create cluster
$ gitops beta run ./dev-cluster --no-session
CTRL+C
$ gitops beta run ./dev-cluster --no-session
```

**Expected behavior**

The application to run again as it did in the first time around, skipping operations already executed (installing Flux and the Dashboard).

**Actual Behavior**

Errors with:
```
E1129 08:46:34.795920   80234 portforward.go:406] an error occurred forwarding 32917 -> 32917: error forwarding port 32917 to pod bdc2c30cd1090feb32118a262528bb18263b067de56cda09cf7c02062acdec49, uid : failed to execute portforward in network namespace "/var/run/netns/cni-d9912606-6b93-9943-58ac-951c91df8ef2": failed to connect to localhost:32917 inside namespace "bdc2c30cd1090feb32118a262528bb18263b067de56cda09cf7c02062acdec49", IPv4: dial tcp4 127.0.0.1:32917: connect: connection refused IPv6 dial tcp6 [::1]:32917: connect: connection refused
E1129 08:46:34.796043   80234 portforward.go:234] lost connection to pod
Error: Put "http://localhost:32917/gitops-run-logs/": dial tcp 127.0.0.1:32917: connect: connection refused
```

**Additional Context (screenshots, logs, etc)**

```sh
$ gitops beta run ./dev-cluster --no-session
► Checking for a cluster in the kube config ...
► Checking if Flux is already installed ...
► Getting Flux version ...
⚠️ Flux is not found: error getting Flux labels
Running Flux command: /home/levi/.cache/.gitops/flux/0.36.0/flux install
✚ generating manifests
✔ manifests build completed
► installing components in flux-system namespace
CustomResourceDefinition/alerts.notification.toolkit.fluxcd.io created
CustomResourceDefinition/buckets.source.toolkit.fluxcd.io created
CustomResourceDefinition/gitrepositories.source.toolkit.fluxcd.io created
CustomResourceDefinition/helmcharts.source.toolkit.fluxcd.io created
CustomResourceDefinition/helmreleases.helm.toolkit.fluxcd.io created
CustomResourceDefinition/helmrepositories.source.toolkit.fluxcd.io created
CustomResourceDefinition/kustomizations.kustomize.toolkit.fluxcd.io created
CustomResourceDefinition/ocirepositories.source.toolkit.fluxcd.io created
CustomResourceDefinition/providers.notification.toolkit.fluxcd.io created
CustomResourceDefinition/receivers.notification.toolkit.fluxcd.io created
Namespace/flux-system created
ServiceAccount/flux-system/helm-controller created
ServiceAccount/flux-system/kustomize-controller created
ServiceAccount/flux-system/notification-controller created
ServiceAccount/flux-system/source-controller created
ClusterRole/crd-controller-flux-system created
ClusterRoleBinding/cluster-reconciler-flux-system created
ClusterRoleBinding/crd-controller-flux-system created
Service/flux-system/notification-controller created
Service/flux-system/source-controller created
Service/flux-system/webhook-receiver created
Deployment/flux-system/helm-controller created
Deployment/flux-system/kustomize-controller created
Deployment/flux-system/notification-controller created
Deployment/flux-system/source-controller created
NetworkPolicy/flux-system/allow-egress created
NetworkPolicy/flux-system/allow-scraping created
NetworkPolicy/flux-system/allow-webhooks created
◎ verifying installation
✔ helm-controller: deployment ready
✔ kustomize-controller: deployment ready
✔ notification-controller: deployment ready
✔ source-controller: deployment ready
✔ install finished
► Checking namespace gitops-run ...
✔ Created namespace gitops-run
► Checking service gitops-run/run-dev-bucket ...
✔ Created service gitops-run/run-dev-bucket
► Checking deployment gitops-run/run-dev-bucket ...
✔ Created deployment gitops-run/run-dev-bucket
► Waiting for deployment run-dev-bucket to be ready ...
► Port forwarding to pod gitops-run/run-dev-bucket-64bf57b76b-5g5vs ...
✔ Port forwarding for run-dev-bucket is ready.
► Checking if GitOps Dashboard is already installed ...
? Would you like to install the GitOps Dashboard? [Y/n] y█
Please enter a password for logging into the dashboard:
► Creating GitOps Dashboard objects ...
✚ Generating GitOps Dashboard manifests ...
► Installing the GitOps Dashboard ...
HelmRelease/flux-system/ww-gitops created
HelmRepository/flux-system/ww-gitops created
✔ GitOps Dashboard has been installed
► Request reconciliation of dashboard (timeout 5m0s) ...
✔ Dashboard reconciliation is done.
► Port forwarding to pod flux-system/ww-gitops-weave-gitops-549469d6d7-rgcgz ...
✔ Port forwarding for dashboard is ready.
► Checking secret run-dev-bucket-credentials ...
✔ Created secret run-dev-bucket-credentials
► Checking bucket source run-dev-bucket ...
✔ Created source run-dev-bucket
► Checking Kustomization run-dev-ks ...
✔ Created ks run-dev-ks
✔ Setup Bucket Source and Kustomization successfully
◎ Press Ctrl+C to stop GitOps Run ...
► 1 change events detected
► Validating files under dev-cluster/ ...
► Refreshing bucket run-dev-bucket ...

► Uploaded 5 files
► Request reconciliation of GitOps Run resources (timeout 5m0s) ...
✔ Reconciliation is done.
^C

$ gitops beta run ./dev-cluster --no-session
► Checking for a cluster in the kube config ...
► Checking if Flux is already installed ...
► Getting Flux version ...
✔ Flux version v0.36.0 is found
► Checking namespace gitops-run ...
✔ Namespace gitops-run already existed
► Checking service gitops-run/run-dev-bucket ...
✔ Service gitops-run/run-dev-bucket already existed
► Checking deployment gitops-run/run-dev-bucket ...
✔ Deployment gitops-run/run-dev-bucket already existed
► Waiting for deployment run-dev-bucket to be ready ...
► Port forwarding to pod gitops-run/run-dev-bucket-64bf57b76b-5g5vs ...
✔ Port forwarding for run-dev-bucket is ready.
E1129 08:46:34.795920   80234 portforward.go:406] an error occurred forwarding 32917 -> 32917: error forwarding port 32917 to pod bdc2c30cd1090feb32118a262528bb18263b067de56cda09cf7c02062acdec49, uid : failed to execute portforward in network namespace "/var/run/netns/cni-d9912606-6b93-9943-58ac-951c91df8ef2": failed to connect to localhost:32917 inside namespace "bdc2c30cd1090feb32118a262528bb18263b067de56cda09cf7c02062acdec49", IPv4: dial tcp4 127.0.0.1:32917: connect: connection refused IPv6 dial tcp6 [::1]:32917: connect: connection refused
E1129 08:46:34.796043   80234 portforward.go:234] lost connection to pod
Error: Put "http://localhost:32917/gitops-run-logs/": dial tcp 127.0.0.1:32917: connect: connection refused
```

**Comment by makkes** [comment] 2022-12-09 14:00
Thanks for reporting this @pjbgf. I looked at the log output you provided and it occurred to me that when you hit CTRL+C nothing is printed afterwards. The fact that the second run says `Namespace gitops-run already existed` backs up my hypothesis that the prior session was still active.

I wonder how you ended up with a running session after hitting CTRL+C. We are aware of this issue when accidentally hitting CTRL+C twice in a row very quickly. In order to further gain information on this, I would like to ask you a favor: Would you please run the command again and then instead of hitting CTRL+C run `kill -TERM $(pidof gitops)` in another shell?

**Comment by pjbgf** [comment] 2022-12-14 18:31
@makkes I gave this a try, but got another error and at the end it asked me whether I wanted to bootstrap into GitOps mode:
![image](https://user-images.githubusercontent.com/5452977/207679747-95ddd5c8-388e-485d-bc03-0308a8d9539e.png)

**Comment by makkes** [comment] 2022-12-16 08:23
Scheduled a meeting with Paulo to investigatte this some more.

**Comment by makkes** [comment] 2023-01-18 12:24
We weren't able to completely reproduce the issue in our meeting.

I'm also not able to reproduce the initial issue so I'm closing the issue for now.

**Closed by makkes** 2023-01-18 12:24 UTC
Labels: bug, severity/high, needs-information, team/denim, gitops-run
