### ISSUE TITLE
Failed to add app using the UI running in the cluster (wego-app) pod

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#938] opened 2021-10-21 20:58 UTC
**Describe the bug**
Using the UI running in the cluster (wego-app pod) I tried to add an application and received the following error:
> Error adding application
could not create app service: error creating git client for app repo: error setting up deploy keys: error retrieving deploy key: error getting deploy key secret: invalid resource name "wego-https://10.96.0.1:443-podinfo-deploy": [may not contain '/']

**Environment**
 - gitops: v0.3.2-rc1
 - kubernetes:  [e.g. 1.21.1]
    - [ ] KinD - 0.11.1]
    - [ ] k3s - _version_
    - [ ] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_
 - Browser + version: [e.g. chrome Version 94.0.4606.61 (Official Build) (x86_64)]
 -
**Affects versions**

**To Reproduce**
1. install wego
2. port forward to the wego-app service
3. open browser to port forward value
4. click add application
5. fill in all the fields
6. click submit

**Expected behavior**
Application is added

**Config and Logs**
If applicable, add logs to help explain your problem. _please compress the output before attaching_

- [ ] - wego-app pod logs
> time="2021-10-21T20:37:19Z" level=info msg="Serving on port 9001"

**Screenshots**

**Additional context**

**Comment by jpellizzari** [comment] 2021-10-29 18:45
Duplicate of #976. Closing.

**Closed by jpellizzari** 2021-10-29 18:45 UTC
Labels: bug, severity/Major
