### ISSUE TITLE
busybox test pod image repository parametric on helm chart

### ISSUE THREAD

**Issue by gsfd2000** [weaveworks/weave-gitops#3117] opened 2022-12-07 12:13 UTC
**Problem**

I tried to deploy the weave-gitops controller via helm chart and wanted to deploy from own own image registry/repository. That was not issue with the controller image, but I got problems with the busybox test pod image as the related registry/repository is not configurable via the helm values.

**Solution**

pls add configuration values to the helm chart so that I can also change the image repository for the busybox test pod image. Best practice would normally be to introduce also a global parameter in the helm values.yaml which sets the registry for all used images. It would be already ok if the busy box image repository can also be configured via values.

**Additional context**

Option would be to set global and image specific parameters, but let's start just with image specific ones, then we just need to add the one for the busybox test image.

**Comment by chanwit** [comment] 2022-12-07 12:53
Hi @gsfd2000 Thank you for filing this issue.

Could you please provider more info on the enhancement you're looking for please?

**Comment by gsfd2000** [comment] 2022-12-07 13:08
strange, I added all the info in  the requested form, do not seem to have stored it.
Problem:
I want to deploy the helm chart of weave-gitops from internal image repository/registry. Whereas this is possible for the major deployment image, it is not possible to configure it for the test pod busybox image.

Solution:
pls add parameters to the values.yaml file to allow also setting the image repository for the test pod busybox image so that that can be configured all from the start.

Additional context:
good helm charts sometimes have the option to set the repository on global level for ALL helm used images AND individual configuration of each single image (if pulled from different registries). However in this case it would already be sufficient to just have a parameter for the busybox repository to change.

**Comment by gsfd2000** [comment] 2022-12-07 13:38
just for understanding, I cannot see the busybox test pod yaml in the helm chart template folder, where is that coming from?
https://github.com/weaveworks/weave-gitops/tree/main/charts/gitops-server/templates

**Comment by gsfd2000** [comment] 2022-12-07 13:44
found it: the image registry/repository for the busy box test pod is not yet paremetric in helm: https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/templates/tests/test-connection.yaml

**Comment by ozamosi** [comment] 2022-12-07 15:18
We should be able to remove this file altogether.

**Comment by gsfd2000** [comment] 2022-12-07 15:32
I would be fine with it, can also attach it later for resting.

**Comment by makkes** [comment] 2022-12-08 09:36
@gsfd2000 you put your remarks in the comments of the PR description (inbetween `<!--` and `-->`), that's why they don't show. I moved them out of the comments and now it looks fine. Thanks for reporting this issue.

**Comment by gsfd2000** [comment] 2022-12-08 10:49
pls educate me shortly where I can see if action is taken on this matter (by when, by who?) and where I can see if it moved into a new update/release. Thx

**Comment by makkes** [comment] 2022-12-08 11:25
Usually when the issue is picked up, you'll see that someone will get assigned to it. Since this is an open source project, we generally take contributions if you would like to move this forward quicker.

**Closed** 2023-10-12 15:48 UTC
Labels: type/enhancement, team/wild-watermelon, priority_low
