### ISSUE TITLE
apparently duplicate entries in add app output

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#1055] opened 2021-11-10 11:34 UTC
**Describe the bug**
In the output of add app we appear to give the same message twice:

```
► Committing and pushing gitops updates for application
► Committing and pushing gitops updates for application
```

i.e:

```
$ gitops add app .
◎ Checking cluster status
✔ GitOps installed
Deploy key generated and uploaded to git provider
Adding application:
Name: podinfo-deploy
URL: ssh://git@github.com/<org>/podinfo-deploy.git
Path: ./
Branch: main
Type: kustomize
✚ Generating Source manifest
✚ Generating GitOps automation manifests
✚ Generating Application spec manifest
► Cloning ssh://git@github.com/<org>/podinfo-deploy.git
Pull Request created: https://github.com/<org>/podinfo-deploy/pull/1
► Applying manifests to the cluster
► Committing and pushing gitops updates for application
► Committing and pushing gitops updates for application
✔ App is up to date
```

**What is the severity of the bug**
Low

**Environment**
 - gitops: [e.g. v0.4.1]
 - kubernetes:  [e.g. 1.20.4]
    - [ ] KinD - _version_]
    - [ ] k3s - _version_
    - [ ] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_
 - Browser + version: [e.g. chrome 74, safari 12, firefox 87]
 -
**Affects versions**

**To Reproduce**
1. gitops add app
2. See error

**Expected behavior**
It would be good to understand if this output is referring to separate actions, and if so decide whether to provide that greater level of information to the user or to aggregate. Or if this is a random duplication

**Comment by palemtnrider** [comment] 2021-11-17 00:33
Duplicate of #941 closing.

**Closed by palemtnrider** 2021-11-17 00:33 UTC
Labels: bug, severity/Low
