### ISSUE TITLE
No padding on Suspend button in Source Detail

### ISSUE THREAD

**Issue by joshri** [weaveworks/weave-gitops#4001] opened 2023-09-11 19:22 UTC
<img width="292" alt="image" src="https://github.com/weaveworks/weave-gitops/assets/65822698/4b7b9fa1-1d67-4056-a0c2-47d0d9e07855">

I can only see it on detail pages for Helm Charts for some reason

**Comment by opudrovs** [comment] 2023-09-15 16:42
@joshri I don't see any issues with Suspend button padding in the latest OSS main or in OSS or enterprise (demo 3) staging:

<img width="1526" alt="Screenshot 2023-09-15 at 18 06 29" src="https://github.com/weaveworks/weave-gitops/assets/8824708/dae66635-0c4a-482c-af72-c7896446f512">

<img width="1504" alt="Screenshot 2023-09-15 at 18 06 36" src="https://github.com/weaveworks/weave-gitops/assets/8824708/03fff91f-f5e1-4810-a737-22e316a53253">

<img width="1530" alt="Screenshot 2023-09-15 at 18 06 55" src="https://github.com/weaveworks/weave-gitops/assets/8824708/0078ed47-67dd-4b1b-a591-595fe9612dbc">

Are you running OSS in Tilt or via `yarn start`?

Could you please re-check the issue?

**Comment by opudrovs** [comment] 2023-09-15 16:44
Tried it with `yarn start`, the padding looks fine to me:

<img width="1522" alt="Screenshot 2023-09-15 at 18 43 46" src="https://github.com/weaveworks/weave-gitops/assets/8824708/3dc38c83-e253-4488-82d7-73d543ce300e">

<img width="1527" alt="Screenshot 2023-09-15 at 18 43 53" src="https://github.com/weaveworks/weave-gitops/assets/8824708/cb07dca3-a23a-4678-898a-96b0d865b8c7">

**Comment by joshri** [comment] 2023-09-15 17:58
@opudrovs - have you checked it out on a Helm Chart? I could only see this on Helm Charts for some odd reason

**Comment by opudrovs** [comment] 2023-09-15 18:13
OK, thanks. Checked HelmChart detail pages locally with Tilt and in staging: I can see that the button looks a bit different indeed and for HelmCharts only. Its padding stays the same, but its width is reduced:  54+ for me instead of 61+. Crazy.

What is weird, I can only see this issue locally
<img width="1531" alt="Screenshot 2023-09-15 at 20 06 30" src="https://github.com/weaveworks/weave-gitops/assets/8824708/ab28bf68-bdbc-4476-aa61-ebd9d1bc83d8">

<img width="1528" alt="Screenshot 2023-09-15 at 20 08 29" src="https://github.com/weaveworks/weave-gitops/assets/8824708/b0906802-0fa0-451a-b3d7-9ccf5cfef4a6">

not in staging:

<img width="1531" alt="Screenshot 2023-09-15 at 20 06 41" src="https://github.com/weaveworks/weave-gitops/assets/8824708/84dc123c-11dd-4823-8a86-eb796b14da2f">

**Comment by opudrovs** [comment] 2023-09-15 18:18
Also see an error I have not seen before with cluster name = Default and cluster not found message. My cluster name is wego-dev and its liveness check is passing fine in Tilt:

<img width="1146" alt="Screenshot 2023-09-15 at 20 15 50" src="https://github.com/weaveworks/weave-gitops/assets/8824708/d28aa192-4b38-4c48-9f80-abcbd15df858">

**Comment by opudrovs** [comment] 2023-09-15 18:19
Have you seen anything like that before?

**Comment by opudrovs** [comment] 2023-09-15 18:21
Besides, there is an issue (more prominent on shorter HelmChart suspend button) with the rotating indicator going beyond the Suspend button boundaries:

https://github.com/weaveworks/weave-gitops/assets/8824708/e281c6e6-6e3b-49bb-9cbe-d0b9710fe880

So, if both of these problems are new, I will create issues for them on Monday.

**Comment by joshri** [comment] 2023-09-15 19:25
> Also see an error I have not seen before with cluster name = Default (in the address bar) and cluster not found message. My cluster name is wego-dev and its liveness check is passing fine in Tilt:
> 
> <img alt="Screenshot 2023-09-15 at 20 15 50" width="1146" src="https://user-images.githubusercontent.com/8824708/268362931-d28aa192-4b38-4c48-9f80-abcbd15df858.png">

hmmmmm - maybe it's expecting `management` to be the name and you don't have a cluster with that name. Not sure.

**Comment by joshri** [comment] 2023-09-15 19:26
> Besides, there is an issue (more prominent on shorter HelmChart suspend button) with the rotating indicator going beyond the Suspend button boundaries:
> 
>  Screen.Recording.2023-09-15.at.20.16.27.mov 
> So, if both of these problems are new, I will create issues for them on Monday.

Yep - hit em with the ui-triage tag

**Comment by opudrovs** [comment] 2023-09-18 11:03
Re-tested it manually, works fine for me in Chrome. Great job! ✨ 

The only minor issue left is that when selecting and copying a portion of YAML in Firefox, blank lines are inserted between YAML lines.

This is what I see when copy=pasting several lines from Chrome (works as expected):

```
metadata:
  annotations:
    metadata.weave.works/CreatedBy: Value 4
    metadata.weave.works/Version: some version
    metadata.weave.works/created-by: Value 2
    metadata.weave.works/createdBy: Value 3
    metadata.weave.works/description: Value 1
    metadata.weave.works/html: <p><b>html</b></p>
    metadata.weave.works/link-to-google: https://google.com
    metadata.weave.works/multi-lines: |
      This is first line
      This is second line
  creationTimestamp: 2023-09-15T15:03:27Z
  finalizers:
    - finalizers.fluxcd.io
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
```

and this is what I see when copy-pasting from Firefox:

```
metadata:

  annotations:

    metadata.weave.works/CreatedBy: Value 4

    metadata.weave.works/Version: some version

    metadata.weave.works/created-by: Value 2

    metadata.weave.works/createdBy: Value 3

    metadata.weave.works/description: Value 1

    metadata.weave.works/html: <p><b>html</b></p>

    metadata.weave.works/link-to-google: https://google.com

    metadata.weave.works/multi-lines: |

      This is first line

      This is second line

  creationTimestamp: 2023-09-15T15:03:27Z

  finalizers:

    - finalizers.fluxcd.io

  generation: 1

  labels:

    kustomize.toolkit.fluxcd.io/name: flux-system

    kustomize.toolkit.fluxcd.io/namespace: flux-system
```

But I think it can be considered a Firefox issue.

**Comment by opudrovs** [comment] 2023-09-18 11:04
Sorry, commented on a wrong issue.

**Comment by opudrovs** [comment] 2023-09-18 13:16
I've raised two issues for issues discovered while researching the current issue:
https://github.com/weaveworks/weave-gitops/issues/4019
https://github.com/weaveworks/weave-gitops/issues/4020

**Comment by opudrovs** [comment] 2023-09-19 19:19
After researching the issue, I can conclude that padding on all pages is the same. The issue is that Suspend button size is set by the length of the status message and `width: 50%` in the `SyncActions` component. (As discussed with @joshri, this 50% width was needed to make the buttons play nice with long Applied Revision and Last Updated messages on Automation details pages).

<img width="1536" alt="Screenshot 2023-09-19 at 15 14 56" src="https://github.com/weaveworks/weave-gitops/assets/8824708/d8b18516-b56a-4e05-94e3-85178280aa77">

<img width="1532" alt="Screenshot 2023-09-19 at 15 22 20" src="https://github.com/weaveworks/weave-gitops/assets/8824708/847b009c-dc1d-4dce-a4be-2fb2617e9330">

<img width="1536" alt="Screenshot 2023-09-19 at 15 22 31" src="https://github.com/weaveworks/weave-gitops/assets/8824708/f7152fab-fdf8-4829-a338-c12591149e9d">

So, now I am checking what can be done about this width. If removing this 50% width, the layout of additional annotation messages on narrow screens changes slightly.

The current layout on narrow screen with 50% setting preserved:

<img width="1031" alt="Screenshot 2023-09-19 at 21 07 49" src="https://github.com/weaveworks/weave-gitops/assets/8824708/7e4aa803-c4fa-471e-93c9-96e5bcd6ac16">

The new layout on narrow screen if this 50% setting is removed:

<img width="1033" alt="Screenshot 2023-09-19 at 21 07 57" src="https://github.com/weaveworks/weave-gitops/assets/8824708/0b871beb-216b-476a-97d4-c8e003a3d73e">

It is possible, it can be fixed with setting a min width somewhere, need more research.

**Closed** 2023-09-21 08:59 UTC
Labels: bug, area/ui, team/tangerine, ui_triage
