### ISSUE TITLE
Graph does not work on macOS Safari 

### ISSUE THREAD

**Issue by stefanprodan** [weaveworks/weave-gitops#2243] opened 2022-05-30 13:06 UTC
On Safari Version 15.4 (17613.1.17.1.13) the graph does not show any labels. 

**Environment**

- Weave-Gitops Version v0.8.1-rc.5
- Flux Version v0.30.2
- Kubernetes version v1.23.5

<img width="1432" alt="Screenshot 2022-05-30 at 15 59 26" src="https://user-images.githubusercontent.com/3797675/170998542-aa4e29d6-97a2-40c2-bce6-e76bec062791.png">

**Comment by opudrovs** [comment] 2022-05-30 17:24
Closed as a duplicate of #2049 .

**Closed by opudrovs** 2022-05-30 17:24 UTC
Labels: bug
