### ISSUE TITLE
gitops run: Session not found error on the GitOps Run session details page

### ISSUE THREAD

**Issue by opudrovs** [weaveworks/weave-gitops#3638] opened 2023-04-24 20:21 UTC
Reported by @steve-fraser 

The GitOps Run session is visible in the GitOps Run sessions table but not found on the GitOps Run details page.

@chanwit pinged you in the thread for more context. Will test GitOps Run UI now too.

**Comment by opudrovs** [comment] 2023-04-24 21:36
![session_not_found_bug_2](https://user-images.githubusercontent.com/8824708/234122156-65e66d3f-e0fd-47b9-bce9-05dfe84d34ed.png)
![session_not_found_bug](https://user-images.githubusercontent.com/8824708/234122159-e28fd1d8-5c85-4616-a103-06a955c498c4.png)

**Comment by chanwit** [comment] 2023-04-25 02:57
It seems to be a case of Helm release which we don't test much. Let's tackle it.

**Comment by opudrovs** [comment] 2023-06-12 20:19
Adding more context from our discussion during the standup and planning. @yiannistri @LappleApple @chanwit 

@chanwit suggested (please correct if I recorded anything wrong) that the reason for this bug is that there is a file watching limit on macOS (possibly with arm64 CPU architecture). Or it is possibly related to using Docker Desktop on macOS or some popular Kubernetes distros like k3s on a Mac.

>The main problem for the mac user is that the Kubernetes or Docker runs on Mac in a virtual machine.

Some of GitOps Run components, like the fluentbit library (used for gathering GitOps Run component logs) use file watching intensively, mainly for watching session components.

A suggested solution might be moving the fluentbit component from within the session to put it directly into the management cluster.

**Comment by opudrovs** [comment] 2023-06-12 20:20
The suggestion to reproduce the issue was to run WGE via Tilt and a GitOps Run session alongside/on the same machine.

I use Kind clusters + Tilt + Docker Desktop on an Intel Mac, and I often run the enterprise UI and GitOps Run together side-by-side, but I have never seen this error.

**Comment by yiannistri** [comment] 2023-06-13 14:39
Closing this issue as we cannot reproduce.

**Closed by yiannistri** 2023-06-13 14:39 UTC
Labels: bug, severity/high, team/wild-watermelon
