### ISSUE TITLE
Avoid possible duplicate flux installation when flux was installed in a different namespace other than `flux-system`

### ISSUE THREAD

**Issue by josecordaz** [weaveworks/weave-gitops#1105] opened 2021-11-18 22:33 UTC
**Short description**
On `gitops install`, if flux is installed in a different namespace, we currently don't detect that and install normally, since we're checking based on whether flux-system exists. Causing duplicate flux installation.

The way to fix this would be by querying all namespaces labels. Flux adds a specific label named `app.kubernetes.io/part-of=flux` when flux is installed. You can test with `kubectl get namespace/flux-system -o jsonpath --template={.metadata.labels}`.

**Environment**
 - gitops: v0.4.1
 - kubernetes:  [e.g. 1.20.4]
    - [ ] KinD - v0.11.1
**Affects versions**

**To Reproduce**
1. Having a clean kind cluster
2. Install flux using bootstrap command and using `my-flux-ns` namespace
```
flux bootstrap github \
  --owner=$GITHUB_USER \
  --repository=fleet-infra \
  --branch=main \
  --path=./clusters/my-cluster \
  --personal \
  --namespace=my-flux-ns
```
3. Run `gitops install ...`
4. It lets the installation succeed.

**Expected behavior**
It should not install weave gitops and warns `Weave GitOps does not yet support installation onto a cluster that is using Flux.\nPlease uninstall flux before proceeding:\n  $ flux uninstall`

**Comment by JamWils** [comment] 2021-11-19 13:17
I would argue that this is in fact, not a bug.  The two systems were never designed to be installed together and now we are doing work to make sure they can be.

**Comment by josecordaz** [comment] 2021-11-19 18:09
you are right, should I close this?

**Comment by josecordaz** [comment] 2021-11-19 19:55
Let's discuss this in refinement to see if we can modify this or we just work on https://app.zenhub.com/workspaces/weaveworks-foss-603cb6b1d4dff9000e242dc4/issues/weaveworks/weave-gitops/1103

**Comment by jpellizzari** [comment] 2021-11-23 16:06
Closing in favor of #1102

**Closed by jpellizzari** 2021-11-23 16:06 UTC
Labels: team/bluetonium
