### ISSUE TITLE
Install Weave Gitops

### ISSUE THREAD

**Issue by markramm** [weaveworks/weave-gitops#64] opened 2021-04-22 14:13 UTC
**Short description**
As a cluster operator I want to install weave gitops into my kubernetes cluster so that application teams can have a gitops repository to manage deployments of that software.

**Acceptance criteria**
- [ ] user is able to specify the branch, the owner, the repo name and the provider flux will use to bootstrap.

**Comment by jrryjcksn** [comment] 2021-04-29 18:26
Duplicate of 90

**Closed** 2021-04-29 18:26 UTC
Labels: type/story
