### ISSUE TITLE
Base url setting for gitops dashboard

### ISSUE THREAD

**Issue by wicharypawel** [weaveworks/weave-gitops#3628] opened 2023-04-17 08:54 UTC
Hello 👋🏻 
recently I was unsuccessful trying to configure and run weave-gitops dashboard for subpath. It would be nice to have a support for base url (aka prefix) configuration.

**Problem**
Weave gitops does not support base url/prefix configuration.

![image](https://user-images.githubusercontent.com/11590420/232435906-6f607e36-6fde-4688-a298-423369bcc469.png)

*Note path to asset file does not contain base url/prefix.*

**Solution**

It would be possible to host weave application at subpath.

```
https://application.com <- application url
https://application.com/internal/gitops/ <- gitops dashboard
https://application.com/internal/gitops/index.html <- gitops dashboard index.html
https://application.com/internal/gitops/index.780a4a15.css <- gitops dashboard asset file
https://application.com/internal/gitops/index.4417e847.js <- gitops dashboard asset file
```

Following ingress configuration would redirect to fully functional application.
```
      - path: /internal/gitops/(.*)
        pathType: Prefix
        backend:
          service:
            name: ww-gitops-weave-gitops
            port:
              number: 9001
```

I would assume that such configuration is defined as a part of a helm release. Suggested property name pathPrefix.

Any help would be greatly appreciated.

**Comment by grebnebo** [comment] 2023-07-13 08:00
It can be done by changing href="/index.css" to href="$uri/index./css"
Also had this bug, trying to change prefix, application always sends to /
So, you can't run app, for example via /flux-ui
Maybe i can help and rewrite this. How to contribute?

**Comment by gre9ory** [comment] 2023-07-18 17:39
@grebnebo 
Did not find anything in this repo close to `href="/index.css"` so no clue how to change it. Can you explain a little more where that change needs to be made, particularly - if possible - in the context of the gitops-server Helm chart?

**Comment by gre9ory** [comment] 2023-09-05 14:28
@grebnebo 
So when rereading your comment I now interpret it as if you had an idea how to implement it and **not** that you know of a way how to do it at this stage? 

Is that correct? If so it was a misunderstanding on my end.

@yiannistri @wicharypawel 
Can you provide any insight into whether this  is coming and if so when to expect it roughly? 
Without being able to host it on a flexible subpath the otherwise nice UI is not usable for us unfortunately.

**Comment by foot** [comment] 2023-09-06 08:34
Hiya! This is mostly a dupe of https://github.com/weaveworks/weave-gitops/issues/2529 but some great conversation and extra context here thank you! Will close here and continue over there.

**Closed by foot** 2023-09-06 08:34 UTC
Labels: enhancement, team/pesto
