### ISSUE TITLE
SYNC additional options does not create a floating menu

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#2228] opened 2022-05-27 10:55 UTC
**Describe the bug**

On the staging cluster I can see that when I click the arrow for the dropdown option "SYNC WITHOUT SOURCE" that it bumps the rest of the content down on the detail page.  This is not the expected behavior.  I would expect for that to be a floating menu option and for it to not adjust any of the content underneath.

**Environment**

- Weave-Gitops Version
main-26c1230

- Flux Version
N/A

- Kubernetes version
v1.22

**To Reproduce**

**Expected behavior**

I would expect for that to be a floating menu option and for it to not adjust any of the content on the detail screen.

**Actual Behavior**

When you click the down arrow the menu appears and pushes content down.  When it is dismissed the content moves back up.

**Additional Context (screenshots, logs, etc)**

![Screen Shot 2022-05-27 at 6.50.23 AM.png](https://images.zenhubusercontent.com/60f5a90306cf76325d5accdc/6058aa23-6359-4aeb-99ba-035f54f276e0)

**Comment by opudrovs** [comment] 2022-06-02 19:48
@JamWils which browser are you using? I'm unable to reproduce the issue in Chrome on Mac.

**Comment by opudrovs** [comment] 2022-06-02 19:50
@JamWils and could you please re-confirm the issue? The recently merged PR for suspend/resume could fix this issue too.

**Comment by opudrovs** [comment] 2022-06-02 21:30
I can confirm a related minor issue in both Chrome and Safari with content slightly pushed down on clicking Sync or Sync without source, probably, because of the icon which is displayed while syncing.

<img width="585" alt="Screenshot 2022-06-02 at 23 22 47" src="https://user-images.githubusercontent.com/8824708/171741127-b33db2e7-1250-4b0f-9710-faaf9273ac6a.png">
<img width="372" alt="Screenshot 2022-06-02 at 23 22 57" src="https://user-images.githubusercontent.com/8824708/171741129-85077681-9840-48a0-9083-f790eb1ab914.png">
<img width="451" alt="Screenshot 2022-06-02 at 23 24 57" src="https://user-images.githubusercontent.com/8824708/171741131-5d11b630-600a-482f-8542-3f12e43a64e7.png">

**Comment by joshri** [comment] 2022-06-06 13:29
Sync button DOES in fact create a floating menu on main (fixed with the addition of the suspend button) - but the button itself weirdly expands now as seen in Olga's screenshot. That should be fixed 🌞

**Closed** 2022-06-07 13:02 UTC
Labels: bug, ui, severity/Low, team/denim
