### ISSUE TITLE
Not working on ARM64

### ISSUE THREAD

**Issue by guidoffm** [weaveworks/weave-gitops#3874] opened 2023-07-23 14:46 UTC
Although I found closed issues that claim there is multi arch support I ran into this problem:

I ran the command 

```
gitup beta run ...
```

The K8s cluster is on Raspberry Pi.

The command created a deployment `run-dev-bucket` that created a pod.

This pod fails with `exec /gitops-bucket-server: exec format error`

```
gitops version
Current Version: 0.28.0
GitCommit: 3ad24e719c66f01efa755072476e3aa5efb3e1c9
BuildTime: 2023-07-19T18:04:30Z
Branch: releases/v0.28.0
```

**Comment by serboctor** [comment] 2023-07-25 07:47
@guidoffm thanks for opening this! We already have another ticket open for it. So I'll link it below and close this one.

Duplicate of #2971

**Closed by serboctor** 2023-07-25 07:47 UTC
Labels: bug
