### ISSUE TITLE
Empty `Type` column in all tables

### ISSUE THREAD

**Issue by stefanprodan** [weaveworks/weave-gitops#2240] opened 2022-05-30 11:55 UTC
After upgrading to v0.8.1-rc.5 the `Type` column is empty on all tables and filtering by Type is broken.

**Environment**

- Weave-Gitops Version v0.8.1-rc.5
- Flux Version v0.30.2
- Kubernetes version v1.23.5

**Expected behavior**

The `Type` should show Kustomization/HelmRelease/GitRepository/etc

**Actual Behavior**

`Type` column is empty on all tables.

<img width="1564" alt="Screenshot 2022-05-30 at 14 54 59" src="https://user-images.githubusercontent.com/3797675/170987294-c10e3c50-4e23-4266-867d-014a869017f2.png">
<img width="1431" alt="Screenshot 2022-05-30 at 14 55 08" src="https://user-images.githubusercontent.com/3797675/170987307-193e19a3-cae7-4704-af30-e75a9595eb4d.png">

**Comment by stefanprodan** [comment] 2022-05-30 11:58
Also the `Source` field in details has a `Kind` prefix that should be removed 

<img width="640" alt="Screenshot 2022-05-30 at 14 57 38" src="https://user-images.githubusercontent.com/3797675/170987736-9c84f6ca-ad75-403a-a15f-044ec80595a2.png">

**Comment by ozamosi** [comment] 2022-05-30 18:09
Main issue is duplicate of #2220, comment is duplicate of #2217

**Closed by ozamosi** 2022-05-30 18:09 UTC
Labels: bug
