### ISSUE TITLE
Upgrade to WGE not possible on EKS cluster

### ISSUE THREAD

**Issue by LutzLange** [weaveworks/weave-gitops#1040] opened 2021-11-05 09:38 UTC
**Describe the bug**
I do need a new updated demo environment for SAs. I try following the official installation documentation.

**What is the severity of the bug**
serverity/Major

The documentation fails to state that you need to add an app. I tried and failed see : 
[Issue 1039 ](https://github.com/weaveworks/weave-gitops/issues/1039)

I guess it is no surprise that the Upgrade fails :  
$ gitops upgrade
Deriving org/repo for PR as weavegitops/demo2-repo
Deriving name of GitRepository Resource as wego-system/demo2-repo
Error: failed to build upgrade configs: couldn't find GitRepository resource "wego-system/demo2-repo" in the cluster, please specify

**Comment by LutzLange** [comment] 2021-11-11 14:48
The GitRepository resource will be created when you add an application. It should not be required to add an application to upgrade the cluster.

**Comment by sympatheticmoose** [comment] 2021-11-11 15:39
This seems a duplicate of https://github.com/weaveworks/weave-gitops/issues/1028 which as commented the docs do state you need to have set up the git repository to sync, but not in the clearest manner.

**Closed by sympatheticmoose** 2021-11-11 15:39 UTC
Labels: bug, severity/Minor
