### ISSUE TITLE
Version in the UI (wego-app pod) doesn't display the correct version and links to an invalid page in GitHub

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#939] opened 2021-10-21 21:05 UTC
**Describe the bug**
The footer on the Weave GitOps page displays the version of v0.3.2 however, the version under test is v0.3.2-rc1

The version link takes you to an invalid page in GitHub

The docs page takes you to a version that doesn't exist (yet) as well.

**Environment**
 - gitops: v0.3.2-rc1
 - kubernetes: 1.21.1
    - [ ] KinD - 0.11.1]
    - [ ] k3s - _version_
    - [ ] cloud [e.g., EKS, AKS]  _version_
    - [ ] other - _name_ _version_
 - Browser + version: [e.g. chrome 74, safari 12, firefox 87]
 -
**Affects versions**
* v0.3.2-rc1
* 
**To Reproduce**
1. install weave gitops
2. open a port to the wego-app service
3. open the page in a browser
4. see the version v0.3.2. 
5. the version is a link - click on it, you are taken to a missing page in GitHub
6. Docs link also goes to an invalid page.

**Expected behavior**
* Printing the complete version number in the footer.
* Linking to that version page in GitHub
* Linking to the correct docs page.

**Comment by jpellizzari** [comment] 2021-10-21 22:28
I feel like that is only a bug if the wrong version is being added to the `href`. This is working as intended for me.

> see the version v0.3.2.

We are pulling the version from the `package.json`, so it should match whatever is in that file.

**Comment by jpellizzari** [comment] 2021-11-04 16:05
This is working as intended. Closing.

**Closed by jpellizzari** 2021-11-04 16:05 UTC
Labels: bug, good first issue, severity/Minor
