### ISSUE TITLE
Failed sync source, service account wego-app does not have the rights on gitrepositories

### ISSUE THREAD

**Issue by mtparet** [weaveworks/weave-gitops#1179] opened 2021-12-06 15:20 UTC
**Describe the bug**
Try to sync a new app and getting :
```
Error syncing Application
error syncing app: failed sync source: error setting resource: gitrepositories.source.toolkit.fluxcd.io "test" is forbidden: User "system:serviceaccount:wego-system:wego-app-service-account" cannot update resource "gitrepositories" in API group "source.toolkit.fluxcd.io" in the namespace "wego-system"
```
**What is the severity of the bug**
Please add a label for this ticket indicating the severity of this bug.  

| Label | Description |
| --- | --- |
| severity/Critical | Weave GitOps is crashing or experiencing data loss, and there is no known workaround |
| severity/Major | Weave Gitops functionality is broken, there is a workaround, and the workaround requires significant effort |
| severity/Minor | Weave Gitops functionality is broken, but there is a workaround |
| severity/Low | Doesn’t affect primary flow/functionality but would be good to fix |

**Environment**
 - gitops: [v0.5.0]
 - kubernetes:  [e.g. 1.22.3]
    - [x] Minikube  [v1.24.0]
 -
**Affects versions**

**To Reproduce**
1. gitops install
2. merge first PR
3. Go to wego-app web app
4. Click on "sync app"
5. See the error

**Expected behavior**
No errors

**Config and Logs**
If applicable, add logs to help explain your problem. _please compress the output before attaching_
- [ ] gitops config
- [ ] `gitops` cli call output (and parameters)
- [ ] gitops-controller logs
- [ ] Events from wego-* namespaces
- [ ] `kubectl cluster-info dump`
- [ ] Prometheus alerts
- [ ] Flux logs

**Screenshots**
![image](https://user-images.githubusercontent.com/754770/144872436-c2be79a5-57e4-4fec-af4d-dbe0d7d3f278.png)

**Additional context**

**Comment by sympatheticmoose** [comment] 2021-12-08 14:10
Thanks for raising this @mtparet! I _believe_ this is a Weave GitOps Enterprise only issue with the on-cluster UI... could you confirm whether you encountered this using the local web app in Core? I am unable to reproduce. A fix is in the works for Enterprise, I will close this issue once it is resolved.

**Comment by foot** [comment] 2021-12-08 15:30
>  I believe this is a Weave GitOps Enterprise only issue with the on-cluster UI

This looks like it could be an issue in both the EE and core UI when they're running in-cluster. More RBAC permissions are required for the wego-app service-account.

I think we need to add `update` here https://github.com/weaveworks/weave-gitops/blob/main/manifests/wego-app/role.yaml.tpl#L24

**Comment by sympatheticmoose** [comment] 2021-12-08 15:36
Thanks @foot!

**Comment by foot** [comment] 2021-12-08 15:49
> in Core we don't really expose that since gitops ui run will start the local web app.

Yes!

@mtparet you're port-forwarding / minikube nodePorting the wego-app deployment?

**Comment by mtparet** [comment] 2021-12-09 12:46
Sorry for not indicate it but yes I was using gitops core (not the entreprise version) and port-forwarding the wego-app.

I created a clusterrolebinding cluster-admin for the wego-app service account to workaround for now. I am just evaluating it so far and trying to understand our our current gitops repositories can fit in this model.

**Closed as completed** 2022-01-14 16:38 UTC
Labels: bug, severity/low, customer issue
